mbudnek/google-home-hubitat-community

README.md, google-home-community.groovy
This adds support for configuring some actions of a device type to require either a confirmation or a PIN code.
The former is mainly useful to prevent accidentally triggering an action.
The latter is intended to secure devices such as doors and locks to prevent their actions from being triggered by unauthorized parties.
Resolves #1
=> Add confirmation and PIN code support

google-home-community.groovy
The device type delete logic was attempting to modify the list of
PIN codes while iterating over it.  This fixes the logic to first
gather the list of PIN codes and then iterate over that temp list.
=> Fix an error deleting device types with PIN codes

google-home-community.groovy
The trait loading function and command execution function were using different names for `openPositionCommand`.
=> Fix OpenClose trait when discreteOnly is not set

google-home-community.groovy
The `importUrl` setting doesn't seem to work for apps, but it does serve as documentation.
=> Add importUrl

google-home-community.groovy
Google will send an `openPercent` parameter in the range [0, 100], but Hubitat uses the range [0, 99], so clamp it so that we pass 99 to the driver when we get 100.
=> Clamp openPercent parameter for non-discrete OpenClose

README.md, google-home-community.groovy
The ColorSetting trait allows a device to have its color set.  It's primarily intended for smart lights.
=> Add support for the ColorSetting trait.

README.md, google-home-community.groovy
This adds support for standalone ambient temperature sensors using the `queryOnlyTemperatureSetting` attribute of the TemperatureSetting trait.
It's not perfect, but this allows you to set up ambient temperature sensors and query their temperature by asking the Google Assistant things like "What's the temperature of {device}?" or "What's the temperature in {room}?".  When you ask for the temperature of a room the assistant will respond with the temperature of each temperature sensor in the room individually.
Closes #14
=> Implement the queryOnlyTemperatureSetting attribute

README.md, google-home-community.groovy
This adds support for the TemperatureControl trait.  This trait is used for devices that can sense and/or control their own internal temperature, such as a water heater or an oven.
There's not really a corresponding device capability in Hubitat for controlling internal temperature, but I can imagine it could be useful for some temperature sensors.
=> Implement TemperatureControl trait

README.md, google-home-community.groovy
This changes the TemperatureSetting trait to use a different command and attribute for getting and setting the setpoint for each mode.  Heat/Cool mode shares its attributes and commands with the Heat and Cool modes.
=> Use different setpoint commands and attributes per mode

google-home-community.groovy
A couple of people have mentioned that they would prefer the device type inputs be sorted by device type name to make it easier to deal with lots of device types.
=> Sort device types by name

google-home-community.groovy
The fahrenheitToCelsius function converts a temperature, not a
number of degrees.  For a number of degrees, we just want the
scale factor, not the extra offset used for temperatures
=> Fix the TemperatureControl temperature step conversion

README.md, google-home-community.groovy
This adds support for the HumiditySetting trait for use for devices like humidifiers, dehumidifiers, and humidity sensors.
Closes #15
=> Add support for the HumiditySetting trait

google-home-community.groovy
Google expects the current humidity reading to be an integer,
but some sensors report fractions of a percent.  Round it off.
=> Fix Humidity Setting when device reports fractions of a percent

README.md, google-home-community.groovy
The Rotation trait is for devices that can be rotated to a specific
position, such as slat blinds or standing fans.
This only implements percentage-based rotation, since there aren't
any Hubitat capabilities that use degree-based rotation.  That can
be implemented later if someone finds a device that uses it.
=> Implement the Rotation trait

README.md, google-home-community.groovy
The volume trait is used to control the volume of things like TVs and speakers.
=> Add support for the Volume trait

google-home-community.groovy, packageManifest.json
This adds support for configuring a device which has no `setVolume` with a set value, allowing to control such devices by using `volumeUp`/`volumeDown` commands.
- On LG WebOS TVs, when using an external sound system with HDMI ARC or Optical connection, the TV ignores any absolute volume specifications, and will only responds to relative changes.
n/a
- The Volume trait settings page was modified to allow specifying either `setVolume` OR `volumeUp` and `volumeDown`.
- All defaults remain as they were. When the new toggle is off, there's effectively no change.
- I also dislike the `pauseexecution` solution, but after significant testing, I don't really see any other way. That said, I'm no Groovy pro, and any comments or suggestions are most welcome.
- Example of the change in the settings …
=> Add support for volume on devices w/o setVolume

google-home-community.groovy, packageManifest.json
The TemperatureControl trait was using the wrong name for the current setpoint attribute.  It also had "setpoint" misspelled in another spot.
=> Fix a bug in the TemperatureControl trait

google-home-community.groovy, packageManifest.json
The SetTemperature handler was passing the wrong thing to the MFA check, which was causing it to fail on a NullPointerException
=> Fix the SetTemperature command of the TemperatureControl trait

google-home-community.groovy, packageManifest.json
When creating a new toggle in the Toggles trait it's possible to
leave the page without filling in any labels by either closing the
browser or clicking a link out of the app.  This would break the
entire app settings due to an error trying to load that bad toggle.
This adds a default "Unknown" label that will be used in that case
so that the app will continue to function and the user can delete
the bad toggle.
=> Avoid breaking the whole app because of a bad toggle

google-home-community.groovy, packageManifest.json
The following new device types have been added since the list was last updated:
* AIRCOOLER
* AUDIO_VIDEO_RECEIVER
* FREEZER
* NETWORK
* ROUTER
* SPEAKER
* STREAMING_BOX
* STREAMING_SOUDBAR
* STREAMING_STICK
=> Add new device types supported by Google

README.md
Some users have gotten hung up on the steps that require extracting
their app ID from the config page URL and building their Google
Action's fulfillment URL using their app ID and hub ID.  This adds
some examples to hopefully make that clearer.
=> Add some examples to the setup instructions

google-home-community.groovy, packageManifest.json
This is an update on top of #42 and includes the commits from that PR in this one.
In this PR, I update each execute handler to return both the attributes to await *and* the new assumed states of the device.
I also changed the logic to keep the poll for the attributes to await when immediate response is enabled, but shorten the poll from 5000 ms to 1000 ms.
For both immediate response and the previous behavior, we now return `PENDING` instead of `SUCCESS` when the device attributes have not yet all been reached.
=> [v2] Allow immediate response

google-home-community.groovy, packageManifest.json
This changes request and response logging to be in JSON so they can be
easily formatted. It's hard to format Groovy's funky `Map.toString()`
output, but there are tons of JSON formatters.
=> Log requests and responses in JSON to make debugging easier

google-home-community.groovy, packageManifest.json
The Toggles trait is unique in that its command executor method
calls the `executeCommand_OnOff` method to do its actual work.  #69
recently changed the return value of the command executors but missed
this one case.  This restores Toggles to full functionality.
=> Fix a bug recently introduced in the Toggles trait

google-home-community.groovy, packageManifest.json
This gracefully handles the case when the `Device` class's `roomId`
property is missing, as is the case on Hubitat versions prior to
2.2.7.  I originally thought it would just be returned as `null`,
but it seems to behave slightly differently than the app class.
=> Fix SYNC handler on Hubitat 2.2.6 and earlier

google-home-community.groovy, packageManifest.json
This fixes #76 by treating level/position of 99 as 100 for Z-Wave devices which don't map their ranges to the Hubitat range of [0..99].
I tested this with Z-Wave dimmers and window blinds.
=> Treat level/position of 99 as 100 instead of trying to scale

README.md, google-home-community.groovy, packageManifest.json
Some window shade device drivers use position 0 to indicate fully
open (AKA 0% unrolled) and 100 to indicate fully closed.  This is
backwards from what Google uses, so add a toggle to support those
drivers.
Closes #26
=> Add a reverseDirection toggle to the Open/Close trait

google-home-community.groovy, packageManifest.json
The app currently doesn't try to reconcile when a device is selected as
multiple device types.  Previously, it would just send two device
configurations to Google with the same ID, causing Google to reject the
SYNC response outright.  This changes the behavior in that situation to
log a warning and ignore subsequent definitions of the same device so
that one misconfigured device doesn't block the user's other devices
from being synced with Google.
=> Log a warning if a device is selected as multiple device types

README.md, codenarc.xml, google-home-community.groovy, packageManifest.json
Added support for the FanSpeed supportsFanSpeedPercent trait.  Works for Hubitat fans having a "level" setting. Allows command using statements like "Set fan to 50 percent"
=> Control Fan Using Percentages

google-home-community.groovy, packageManifest.json
This adds error handling to QUERY intent requests to avoid having one
misconfigured device prevent all other devices from reporting.
=> Add error handling on QUERY intents

google-home-community.groovy, packageManifest.json
Previously we were only rounding temperatures if we did a conversion.
This changes all temperature handling to round to one decimal place
regardless of if we do a conversion or not.
=> Normalize rounding of temperatures to one decimal place

google-home-community.groovy, packageManifest.json
There was a NullPointerException reported from passing null into the
roundTo method.  I'm not exactly sure what's null that's being passed
in, so this makes the method tolerate the null and generate a stack
trace so I can track it down.
=> Tolerate attempting to round null

google-home-community.groovy, packageManifest.json
The various SensorState types were all appearing as `[object Object]` in the settings UI since the map being used for the choices has maps as its values.  This does a transform to extract the labels correctly.
=> Fix SensorState labels in settings UI

README.md
It seems like portal.hubitat.com no longer exists, but you can get your Hub ID directly from the hub now anyway
=> Update instructions for getting Hub ID

google-home-community.groovy, packageManifest.json
The app was getting bad request errors when trying to report state for stateless devices like scenes and modes.  This avoids attempting to report state for devices with no states.
=> Small fix to avoid trying to report empty device state

google-home-community.groovy, packageManifest.json
This PR includes a tweak to the error reporting when posting device state requests so that failures will also output the request body that caused the error. I found it easier to include in the error message as there's less content in the logs to dig through to identify the request that failed. No problem if you want me to remove this as I see that debug logging can be enabled to output the same info if needed.
=> Uppercase values sent for MediaState attributes

google-home-community.groovy, packageManifest.json
The hubVersionLessThan function would incorrectly return true if the hub version was greater than the target version but contained a piece that was less than the corresponding piece in the target version.  For example, 2.3.5.103 would be considered less than 2.3.4.115 because 103 is less than 115 even though comparison should have stopped after comparing 5 to 4.
=> Fix hub version comparison
