mbudnek/google-home-hubitat-community

google-home-community.groovy
* `!!foo` -> `foo as boolean`
* removed empty app lifecycle methods
* `videoCapture` capability was duplicated, one should be `videoCamera`
=> Clean up some things found by linting

google-home-community.groovy
I forgot some quotes, so this was checking `result[null]` instead of `result["status"]`.
=> Fix device state reporting after executing an action

google-home-community.groovy
The `LockUnlock` trait implementation is fairly similar to `OnOff`, but is less flexible for now.  It only allows for one "locked" value and I haven't implemented support for the `isJammed` state since I'm not aware of any Hubitat lock drivers that can detect that.
=> Add support for the LockUnlock trait

google-home-community.groovy
Not sure how that snuck in there
=> Remove an errant backtick

google-home-community.groovy
* Several TemperatureSetting and TemperatureControl settings used the wrong input type of "real" instead of "decimal"
* I was using fahrenheitToCelsius to convert the heat/cool buffer from fahrenheit to celsius, but that converts a temperature, not a number of degrees.
* The "off" mode shouldn't have setpoint get/set settings.  It has no setpoint.
=> Fix some issues with the TemperatureSetting and TemperatureControl traits

google-home-community.groovy
Since scene activation often requires sending messages to several
devices, it can sometimes take long enough that the request from
Google Home times out, causing the assistant to report an error
even though the command was ultimately successful.  This changes
scene control to run asynchronously to work around this issue.
=> Make scene control asynchronous

google-home-community.groovy
Oops, forgot to do this in #29.
=> Update changelog for the Rotation trait

google-home-community.groovy
I was having a problem every time Google would sync devices something wasn't found. For the life of me I couldn't figure out what had happened. Also, the sync would never finish completely because It was erroring out. The additional couple lines of code allowed me to track down the offending device and add it back to the app. But even before I was able to do that, it allowed the sync to finish successfully rather than erroring out. 
I know it's a tiny little change but I figured out I would pass it along since it made a big impact to me.  Thanks!
=> Added Check for deviceInfo Being Null

google-home-community.groovy
This works around the hacky way I'm working around the fact that
Hubitat doesn't let you define your own exception classes.
If command execution throws an exception, we now first try to parse
that exception's message as JSON to generate a specific error response.
If that fails, we log the error and report a hard error back to Google.
=> Handle command execution errors better

codenarc.xml, google-home-community.groovy
Add a CodeNarc config file to better control what checks are done
by codefactor.io as part of the pull request gate.
=> Add a CodeNarc config file

README.md
Google made some small changes to their Actions Console UI, so
update the setup instructions to match the new UI.
=> Update setup instructions to reflect Google UI changes

README.md, google-home-community.groovy, packageManifest.json
Add ability to set Global PIN Codes that will be checked for all secured actions.
=> Add Global PIN Codes

google-home-community.groovy, packageManifest.json
Added Dock and StartStop traits, cleaned up blanks spaces etc..
=> Added Dock and StartStop traits

README.md
Also cleaned up some trailing spaces and tabs
=> Update readme with note about copying from OAuth dialog

google-home-community.groovy, packageManifest.json
Fixed missing JSON braces for Energy Storage trait capacityUntilFull.
=> Fixed missing JSON braces for Energy Storage trait capacityUntilFull.

google-home-community.groovy
Update the year, and change it to correctly reflect that I am not the sole copyright holder for this code.
=> Update copyright notice

README.md, google-home-community.groovy, packageManifest.json
Added sensor state trait to allow querying Co, CO2, smoke, rain, filter life, etc sensors for descriptive state as well as numerical value if applicable.
Quantized the set temperature to 0.1 degrees to address Google's large multiple decimal place floating point math.
=> Added sensor state trait.  

README.md, google-home-community.groovy, packageManifest.json
Added Transport Control. Supported commands are those that align with the commands available on the Hubitat Music Player capability.
=> Added Transport Control

packageManifest.json
Somehow I managed to not commit this file in #97
=> Update version number in package manifest

README.md, google-home-community.groovy, packageManifest.json
The OccupancySensing trait is useful for things like motion sensors
=> Add support for the OccupancySensing trait

codenarc.xml, google-home-community.groovy, hubitat-virtual-blueiris-camera-stream-object.groovy, hubitat-virtual-generic-camera-stream-object.groovy, packageManifest.json
The CodeNarc checks were crashing because CodeNarc removed one of their rule classes.  This removes that rule from the config and adds the new rules that have been added since I last updated it.  It also fixes all of the issues that have crept in since the checs haven't been running.
=> Fix CodeNarc and enable new rules
